title = "Jaswant Singh Taur"

# 1. Replace hsrai with your userID on code.gndec.ac.in server
#baseURL = "http://code.gndec.ac.in/~cse_jaswanttaur/www"
# 2. Type # at the beginning of above line

# 2. Remove # from line below and replace hsrai with your userID at github 
baseURL = "https://jaswanttaur.github.io/www"

# 2. Remove # from line below
publishDir = "docs"

# 2. Type # at the beginning of line below
#publishDir = "../public_html/www"

languageCode = "en-us"
theme = "anatole"
themesDir = "themes"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 4 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  title = "Jaswant Taur"
  favicon = "/images/favicon.ico"
  profilePicture = "https://jaswanttaur.github.io/www/images/logo.png"
  site_logo = "https://jaswanttaur.github.io/www/images/logo.png"
  description = "UI/UX Expert and Cloud Architect"
  Facebook = "https://facebook.com/jaswanttaur"
  twitter = "https://twitter.com/jaswanttaur"
  instagram = "https://instagram.com/jaswanttaur"
  youtube = ""
  github = "https://github.com/jaswanttaur"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3
